core/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('users/', include('users.urls')),
    path('orders/', include('orders.urls')),
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path
from .views import MyOrderView, CreateOrderProductView

app_name = 'orders'


urlpatterns = [
    path('',MyOrderView.as_view(), name='my_orders' ),
    path('add-item/', CreateOrderProductView.as_view(), name='add-item' ),
    
]

products/urls.py
from django.urls import path
from .views import ProductFormView, ProductsListView

app_name = 'products'

urlpatterns = [
    path('', ProductsListView.as_view(), name='list_products'),
    path('add/', ProductFormView.as_view(), name='add_product'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

app_name = 'users'

urlpatterns = [
    path('login/',
         LoginView.as_view(template_name='users/login.html'), 
         name='login'
        ),
    path('logout/',
         LogoutView.as_view(), 
         name='logout'
        ),
]

orders/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product
# Create your models here.


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    order_date = models.DateField(auto_now_add=True)
    
    def __str__(self) -> str:
        return f"order {self.id} by {self.user.username}"
    
    
class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.IntegerField()
    
    
    def __str__(self) -> str:
        return f"{self.order} - {self.product}"

products/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name='nombre')
    description = models.TextField(max_length=300, verbose_name='description')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='precio')
    available = models.BooleanField(default=True, verbose_name='disponible')
    photo = models.ImageField(upload_to='logos', blank=True, null=True, verbose_name='foto')
    
    
    def __str__(self) -> str:
        return self.name

users/models.py
from django.db import models

# Create your models here.

orders/forms.py
from django.forms import ModelForm
from .models import OrderProduct

class OrderProductForm(ModelForm):
    class Meta:
        model = OrderProduct
        fields = ['product']

products/forms.py
from django import forms
from .models import Product

class ProductForm(forms.Form):
    name = forms.CharField(max_length=200, label="Nombre")
    description = forms.CharField(max_length=300, label="Descripcion")
    price = forms.DecimalField(max_digits=10, decimal_places=2, label="Precio")
    available = forms.BooleanField(initial=True, label="Disponible", required=False)
    photo = forms.ImageField(label="Foto", required=False)
    
    
    def save(self):
        Product.objects.create(
            name = self.cleaned_data['name'],
            description = self.cleaned_data['description'],
            price = self.cleaned_data['price'],
            available = self.cleaned_data['available'],
            photo = self.cleaned_data['photo'],
        )

orders/views.py
from django.views.generic import DetailView, CreateView
from .models import Order
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import OrderProductForm
from django.urls import reverse_lazy
# Create your views here.

class MyOrderView(LoginRequiredMixin, DetailView):
    model = Order
    template_name = 'orders/my_orders.html'
    context_object_name = 'order'
    
    def get_object(self, queryset=None):
        return Order.objects.filter(is_active=True, user=self.request.user).first()


class CreateOrderProductView(LoginRequiredMixin, CreateView):
    template_name = 'orders/create_order.html'
    form_class = OrderProductForm
    success_url = reverse_lazy('orders:my_orders')
    
    def form_valid(self, form):
        order, _ = Order.objects.get_or_create(
            is_active=True,
            user = self.request.user
        )
        
        form.instance.order = order
        form.instance.quantity = 1
        form.save()
        return super().form_valid(form)
    

products/views.py
from django.urls import reverse_lazy
from django.views import generic
from .forms import ProductForm
from .models import Product


class ProductsListView(generic.ListView):
    model = Product
    template_name = 'products/products.html'
    context_object_name = 'products'


class ProductFormView(generic.FormView):
    template_name = 'products/add_product.html'
    form_class = ProductForm
    success_url = reverse_lazy('products:list_products')
    
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
     

users/views.py
from django.shortcuts import render

# Create your views here.

templates/includes/navbar.html
<div>
    <div class="sm:hidden">
      <label for="Tab" class="sr-only">Tab</label>
  
      <select id="Tab" class="w-full rounded-md border-gray-200">
        <option>Settings</option>
        <option>Messages</option>
        <option>Archive</option>
        <option select>Notifications</option>
      </select>
    </div>
  
    <div class="hidden sm:block">
      <nav class="flex gap-6" aria-label="Tabs">
        <a
          href="#"
          class="shrink-0 rounded-lg p-2 text-sm font-medium text-gray-500 hover:bg-gray-50 hover:text-gray-700"
        >
          Settings
        </a>
  
        <a
          href="#"
          class="shrink-0 rounded-lg p-2 text-sm font-medium text-gray-500 hover:bg-gray-50 hover:text-gray-700"
        >
          Messages
        </a>
  
        <a
          href="#"
          class="shrink-0 rounded-lg p-2 text-sm font-medium text-gray-500 hover:bg-gray-50 hover:text-gray-700"
        >
          Archive
        </a>
  
        {% if user.is_authenticated  %}
            <form action="{% url "users:logout" %}" method="post">
                {% csrf_token %}
                <button class="shrink-0 rounded-lg bg-sky-100 p-2 text-sm font-medium text-sky-600" type="submit">Log Out</button>
            </form>
        {% endif %}
      </nav>
    </div>
  </div>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hossaik Coffe{% block title %}{% endblock  %}</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>


    {% include "./includes/navbar.html" %}


    <div class="container mx-auto px-4">
        {% block content %}
    
    
        {% endblock  %}
    </div>
    
</body>
</html>

templates/orders/create_order.html
{% extends '../index.html' %}


{% block title %}create Order{% endblock  %}

{% block content %}

    <h2>Create order</h2>

{% endblock  %}

templates/orders/my_orders.html
{% extends '../index.html' %}


{% block title %}Orders{% endblock  %}

{% block content %}

    <h2>Orders</h2>
    
    {{order.user.username}}

    {% for product_order in order.orderproduct_set.all %}
        {{product_order.product.name}}
        {{product_order.product.price}}
    {% empty %}
        no hay items
    {% endfor %}

{% endblock  %}

templates/products/add_product.html
{% extends '../index.html' %}


{% block title %}Create Product{% endblock  %}

{% block content %}

    <form action="{% url "products:add_product" %}" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Add</button>
    </form>

{% endblock  %}

templates/products/products.html
{% extends '../index.html' %}


{% block title %}Create Product{% endblock  %}

{% block content %}

    <h1 class="text-3xl font-bold">
        Products list
    </h1>

    {% for product in products %}

    <a href="#" class="group relative block overflow-hidden">
        <button
          class="absolute end-4 top-4 z-10 rounded-full bg-white p-1.5 text-gray-900 transition hover:text-gray-900/75"
        >
          <span class="sr-only">Wishlist</span>
      
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            class="h-4 w-4"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z"
            />
          </svg>
        </button>
      
        {% if product.photo %}
            <img
            src="{{ product.photo.url }}"
            alt="{{ product.name }}"
            class="h-64 w-full object-cover transition duration-500 group-hover:scale-105 sm:h-72"
        />
        
        {% endif %}
      
        <div class="relative border border-gray-100 bg-white p-6">
            
            {% if product.available %}
              <span class="whitespace-nowrap bg-yellow-400 px-3 py-1.5 text-xs font-medium">Available !!  </span>
            {% endif %}

          <h3 class="mt-4 text-lg font-medium text-gray-900">{{product.name}}</h3>
      
          <p class="mt-1.5 text-sm text-gray-700">${{product.price}}</p>
      
          <form action="{% url "orders:add-item" %}" class="mt-4" method="post">
            {% csrf_token %}
            <input type="hidden" name="product" value={{product.id}}>
            <button
              class="block w-full rounded bg-yellow-400 p-4 text-sm font-medium transition hover:scale-105"
            >
              Add to Cart
            </button>
          </form>
        </div>
      </a>

    {% endfor %}

    
    
{% endblock  %}

templates/users/login.html
{% extends '../index.html' %}
{% load tailwind_filters %}

{% block title %}Login{% endblock  %}

{% block content %}
    <h2 class="text-2xl font-bold text-gray-900 sm:text-3xl">Login form </h2>
    <form action="{% url "users:login" %}" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit"
        class="inline-block rounded border border-indigo-600 bg-indigo-600 px-12 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-indigo-600 focus:outline-none focus:ring active:text-indigo-500"
        href="#"
        >
        Login
    </button>

    </a>
    </form>

{% endblock  %}